-- DEPRECATED: Do not run this file alone.
-- The contests Hive Mind schema (and the rest of the app schema/RLS) lives in:
--   supabase/schema.sql
-- Run that file in the Supabase SQL Editor for a fresh project.
