-- DEPRECATED: contests-only file.
-- Use supabase/schema.sql (or Project store docs/supabase-bootstrap.sql) for a fresh project.
-- Contests remain TEXT-id Hive Mind columns inside that bootstrap (public.contests).
