// AUTO-GENERATED by scripts/sync-shared.mjs from src/lib/utils/sanitizeContestUrl.ts — do not edit.
export function sanitizeContestUrl(url: string): string {
  if (!url || typeof url !== 'string') return url
  let u = url.trim()
  // Strip common feed path suffixes - never send users to RSS/XML
  const feedSuffixes = [
    /\/feed\/?$/i,
    /\/rss\/?$/i,
    /\/atom\/?$/i,
    /\/atom\.xml\/?$/i,
  ]
  for (const re of feedSuffixes) {
    u = u.replace(re, '')
  }
  return u.replace(/\/$/, '') || u
}
