#!/usr/bin/env node
/**
 * Keeps code that must behave identically on every platform in one place.
 *
 *  1. Autofill engine: shared/autofill/engine.js →
 *       src/lib/autofill/engine.generated.ts, mobile/src/lib/autofill/engine.generated.ts,
 *       extension/lib/engine.generated.js
 *  2. Feed core (web src/ is the source of truth):
 *       src/lib/{data,utils,feed}/… → mobile/src/lib/… (verbatim)
 *       src/lib/data/… → supabase/functions/_shared/feed/*.ts (flattened, Deno .ts imports)
 *
 *  3. supabase/setup/{full_setup,latest_update}.sql — paste-ready SQL Editor bundles
 *
 * `npm run sync:shared` writes; `npm run sync:shared -- --check` fails if anything is stale.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8')
const banner = (from) =>
  `// AUTO-GENERATED by scripts/sync-shared.mjs from ${from} — do not edit.\n`

const outputs = {}

// ---- 1. Autofill engine -------------------------------------------------------------------
const engineSrc = read('shared/autofill/engine.js')
const start = engineSrc.indexOf('function loonieAutofill(')
if (start < 0) throw new Error('shared/autofill/engine.js must define function loonieAutofill(')
const fn = engineSrc.slice(start).trim()
const tsModule =
  banner('shared/autofill/engine.js') +
  '/* eslint-disable */\n' +
  '/** Source of the self-contained `loonieAutofill(profile)` function, for page injection. */\n' +
  `export const AUTOFILL_ENGINE_SOURCE: string = ${JSON.stringify(fn)}\n`
outputs['src/lib/autofill/engine.generated.ts'] = tsModule
outputs['mobile/src/lib/autofill/engine.generated.ts'] = tsModule
outputs['extension/lib/engine.generated.js'] = banner('shared/autofill/engine.js') + `export ${fn}\n`

// ---- 2a. Feed core mirrored to mobile ------------------------------------------------------
const MOBILE_MIRROR = [
  'src/lib/data/sources.ts',
  'src/lib/data/tagger.ts',
  'src/lib/data/normalizer.ts',
  'src/lib/data/valuationDictionary.ts',
  'src/lib/utils/sanitizeContestUrl.ts',
  'src/lib/utils/expiryDate.ts',
  'src/lib/utils/linkHealth.ts',
  'src/lib/feed/filters.ts',
  'src/lib/feed/ranking.ts',
  'src/lib/earn/rewards.ts',
]
for (const rel of MOBILE_MIRROR) {
  outputs[rel.replace(/^src\//, 'mobile/src/')] =
    banner(rel) + read(rel).replace(/^\/\/ AUTO-GENERATED[^\n]*\n/, '')
}

// ---- 2b. Feed core for Supabase Edge Functions (Deno needs explicit .ts specifiers) --------
const DENO_FEED = {
  'sources.ts': 'src/lib/data/sources.ts',
  'tagger.ts': 'src/lib/data/tagger.ts',
  'normalizer.ts': 'src/lib/data/normalizer.ts',
  'valuationDictionary.ts': 'src/lib/data/valuationDictionary.ts',
  'sanitizeContestUrl.ts': 'src/lib/utils/sanitizeContestUrl.ts',
  'expiryDate.ts': 'src/lib/utils/expiryDate.ts',
}
for (const [name, rel] of Object.entries(DENO_FEED)) {
  const code = read(rel).replace(
    /(from\s+['"])(\.{1,2}\/[^'"]+)(['"])/g,
    (_m, pre, spec, post) => `${pre}./${path.basename(spec).replace(/\.ts$/, '')}.ts${post}`
  )
  outputs[`supabase/functions/_shared/feed/${name}`] = banner(rel) + code
}

// ---- 3. Paste-ready SQL bundles for the Supabase SQL Editor ----------------------------------
// Everything is idempotent, so both files are safe to run more than once.
const migrations = fs
  .readdirSync(path.join(root, 'supabase/migrations'))
  .filter((f) => f.endsWith('.sql') && !f.includes('cron')) // pg_cron jobs embed keys — set up separately
  .sort()
const sqlPart = (rel) => `-- ===== ${rel} =====\n${read(rel).trim()}\n`
const sqlBanner = (what) =>
  `-- LoonieWins — ${what}\n-- AUTO-GENERATED by scripts/sync-shared.mjs — do not edit. Safe to run more than once.\n` +
  `-- Supabase Dashboard → SQL Editor → New query → paste everything → Run.\n\n`
outputs['supabase/setup/full_setup.sql'] =
  sqlBanner('FULL setup (fresh or partially set-up project)') +
  [sqlPart('supabase/schema.sql'), ...migrations.map((f) => sqlPart(`supabase/migrations/${f}`))].join('\n')
outputs['supabase/setup/latest_update.sql'] =
  sqlBanner('latest update (economy hardening + instant feed + earn more)') +
  migrations
    .filter((f) => f >= '20260925')
    .map((f) => sqlPart(`supabase/migrations/${f}`))
    .join('\n')

// ---- write / check ------------------------------------------------------------------------
const check = process.argv.includes('--check')
let stale = 0
for (const [rel, content] of Object.entries(outputs)) {
  const file = path.join(root, rel)
  const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null
  if (current === content) continue
  if (check) {
    console.error(`stale: ${rel} (run npm run sync:shared)`)
    stale++
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true })
    fs.writeFileSync(file, content)
    console.log(`wrote ${rel}`)
  }
}
if (stale) process.exit(1)
